### ISSUE TITLE
Code Generation Not Working on Mac

### ISSUE THREAD

**Issue by lalluanthoor** [fmvilas/swagger-node-codegen#4]
Error Message
```
Done!
fs.js:50
    throw new TypeError('"options" must be a string or an object, got ' +
    ^

TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:50:11)
    at Object.fs.writeFile (fs.js:1184:13)
    at /Users/lalluanthoor/node_modules/swagger-node-codegen/dist/codegen.js:127:18
    at tryToString (fs.js:425:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
```

I went into the source and removed `, 0` from all the lines with `_fs2.default.writeFile(target_file, content, 0, 'utf8', function (err) {`. After that the code is generated properly. But when I say `make build` it fails with error:

```
...
Building API...
[08:21:19] Using gulpfile ~/swagger/gulpfile.js
[08:21:19] Starting 'build'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: /Users/lalluanthoor/swagger/src/api/routes/author.js: Duplicate declaration "err_response"
  37 |       const err_response = { status: 401, message: 'unauthorized' };
  38 |       return res.status(401).send(err_response);
> 39 |       const err_response = { status: 404, message: 'author not found' };
     |             ^
  40 |       return res.status(404).send(err_response);
  41 |       const err_response = { status: 500, message: 'internal server error' };
  42 |       return res.status(500).send(err_response);
    at File.buildCodeFrameError (/Users/lalluanthoor/swagger/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at Scope.checkBlockScopedCollisions (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/scope/index.js:398:27)
    at Scope.registerBinding (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/scope/index.js:592:16)
    at Scope.registerDeclaration (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/scope/index.js:496:14)
    at Object.BlockScoped (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/scope/index.js:244:28)
    at Object.newFn (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/path/context.js:44:14)
    at NodePath.visit (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/lalluanthoor/swagger/node_modules/babel-traverse/lib/context.js:150:16)
make: *** [build] Error 1
```

Config
```
$ node --version
v7.0.0

$ npm --version
3.10.8
```

**Comment by fmvilas** [comment]
Hey @lalluanthoor thanks for reporting. The first one seems to be related to recent changes on fs.writeFile API. The second one I have no idea. I'll check this weekend.

If you can use a previous Node.js version I would suggest you to do it in the meantime. I guess version 6 should be fine.

**Comment by lalluanthoor** [comment]
Hi @fmvilas,
With Node 6 I was able to run the generator. But facing same issue with build. Tried it on Node v6 on a Windows machine as well as Node v7 on Mac.

Have a look at [my repository](https://github.com/lalluanthoor/swagger-lms). I've also put the `swagger.json` there.

**Comment by fmvilas** [comment]
Hey, thanks for sharing your code. I found 2 problems:

1. The default should be `200` not `500`:
https://github.com/fmvilas/swagger-node-codegen/blob/master/templates/src/api/routes/___route.js#L43
A Pull Request would be much appreciated here since I don't have so much time lately.

2. You get [repeated `const` declarations](https://github.com/lalluanthoor/swagger-lms/blob/master/src/api/routes/author.js#L37) because of this line:
https://github.com/fmvilas/swagger-node-codegen/blob/master/templates/src/api/routes/___route.js#L40
Please, note that this module is just for boilerplate generation. You should now go there and decide what constitutes a `401`, a `404` and a `500`. This is up to your business logic. It's not something the code generator can guess.

Hope it helps!

**Comment by lalluanthoor** [comment]
Hi,

I'll take care of 1.

For 2, should I change the generated code to rename variables?

**Comment by lalluanthoor** [comment]
@fmvilas PR submitted.

**Comment by fmvilas** [comment]
> For 2, should I change the generated code to rename variables?

Yes. That would be good enough.

Thanks for the PR!

**Comment by lalluanthoor** [comment]
closing since PR is merged.
